using System;
using System.Globalization;
using Content.Shared.PowerTransmissionLaser;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Localization;
using Robust.Shared.Maths;
using Content.Client.UserInterface.Controls;

namespace Content.Client.PowerTransmissionLaser;

[GenerateTypedNameReferences]
public sealed partial class PowerTransmissionLaserWindow : FancyWindow
{
    private float _minPrice;
    private float _maxPrice;
    private float _stepSmall;
    private float _stepLarge;
    private bool _updatingControls;

    public event Action<bool>? OnToggle;
    public event Action<float>? OnSetPrice;
    public event Action<float>? OnAdjustPrice;

    public PowerTransmissionLaserWindow()
    {
        RobustXamlLoader.Load(this);

        EnabledCheckBox.OnToggled += _ =>
        {
            if (_updatingControls)
                return;
            OnToggle?.Invoke(EnabledCheckBox.Pressed);
        };

        PriceSpinBox.IsValid += PriceIsValid;
        PriceSpinBox.OnValueChanged += OnPriceChanged;

        PriceDownSmall.OnPressed += _ => OnAdjustPrice?.Invoke(-_stepSmall);
        PriceUpSmall.OnPressed += _ => OnAdjustPrice?.Invoke(_stepSmall);
        PriceDownLarge.OnPressed += _ => OnAdjustPrice?.Invoke(-_stepLarge);
        PriceUpLarge.OnPressed += _ => OnAdjustPrice?.Invoke(_stepLarge);
    }

    private bool PriceIsValid(float value)
        => value >= _minPrice && value <= _maxPrice;

    private void OnPriceChanged(FloatSpinBox.FloatSpinBoxEventArgs args)
    {
        if (_updatingControls)
            return;

        var clamped = Math.Clamp(args.Value, _minPrice, _maxPrice);
        if (!MathHelper.CloseTo(clamped, args.Value))
        {
            _updatingControls = true;
            PriceSpinBox.Value = clamped;
            _updatingControls = false;
        }

        OnSetPrice?.Invoke(clamped);
    }

    public void Update(PowerTransmissionLaserBuiState state)
    {
        _updatingControls = true;

        _minPrice = state.MinPrice;
        _maxPrice = state.MaxPrice;
        _stepSmall = state.StepSmall;
        _stepLarge = state.StepLarge;

        EnabledCheckBox.Pressed = state.Enabled;
        EnabledCheckBox.Disabled = !state.Anchored;

        PriceSpinBox.Value = state.PricePerMegawatt;

        PriceDownSmall.Text = Loc.GetString("power-transmission-laser-ui-button-price-down-small", ("step", FormatStep(_stepSmall)));
        PriceUpSmall.Text = Loc.GetString("power-transmission-laser-ui-button-price-up-small", ("step", FormatStep(_stepSmall)));
        PriceDownLarge.Text = Loc.GetString("power-transmission-laser-ui-button-price-down-large", ("step", FormatStep(_stepLarge)));
        PriceUpLarge.Text = Loc.GetString("power-transmission-laser-ui-button-price-up-large", ("step", FormatStep(_stepLarge)));

        PriceDownSmall.Disabled = PriceUpSmall.Disabled = PriceDownLarge.Disabled = PriceUpLarge.Disabled = !state.Anchored;

        var statusKey = GetStatusKey(state);
        StatusLabel.Text = Loc.GetString(statusKey);
        StatusLabel.StyleClasses.Clear();
        StatusLabel.StyleClasses.Add("LabelKeyText");
        StatusLabel.StyleClasses.Add(GetStatusStyle(state));

        PowerValue.Text = Loc.GetString("power-transmission-laser-ui-power-value", ("power", FormatNumber(state.LastPowerMegawatts)));
        MaxPowerValue.Text = Loc.GetString("power-transmission-laser-ui-power-value", ("power", FormatNumber(state.MaxPowerDrawMegawatts)));
        EnergyValue.Text = Loc.GetString("power-transmission-laser-ui-energy-value", ("energy", FormatNumber(state.TotalEnergyMegajoules)));
        RevenueValue.Text = Loc.GetString("power-transmission-laser-ui-revenue-value", ("credits", FormatNumber(state.TotalRevenue, 0)));

        var pending = state.PendingCredits;
        PendingValue.Text = state.BankAvailable
            ? Loc.GetString("power-transmission-laser-ui-pending-value", ("credits", FormatNumber(pending)))
            : Loc.GetString("power-transmission-laser-ui-pending-held", ("credits", FormatNumber(pending)));

        LastValue.Text = Loc.GetString("power-transmission-laser-ui-last-value", ("credits", FormatNumber(state.LastPayout, 0)));
        BankValue.Text = state.BankAvailable
            ? Loc.GetString("power-transmission-laser-ui-bank-connected")
            : Loc.GetString("power-transmission-laser-ui-bank-missing");
        ApcValue.Text = state.ApcPowered
            ? Loc.GetString("power-transmission-laser-ui-apc-powered")
            : Loc.GetString("power-transmission-laser-ui-apc-unpowered");
        AnchorValue.Text = state.Anchored
            ? Loc.GetString("power-transmission-laser-ui-anchor-anchored")
            : Loc.GetString("power-transmission-laser-ui-anchor-unanchored");

        _updatingControls = false;
    }

    private static string GetStatusKey(PowerTransmissionLaserBuiState state)
    {
        if (!state.Anchored)
            return "power-transmission-laser-ui-status-unanchored";
        if (!state.ApcPowered)
            return "power-transmission-laser-ui-status-unpowered";
        if (!state.Enabled)
            return "power-transmission-laser-ui-status-disabled";
        if (state.LaserActive)
            return "power-transmission-laser-ui-status-active";
        return "power-transmission-laser-ui-status-idle";
    }

    private static string GetStatusStyle(PowerTransmissionLaserBuiState state)
    {
        if (!state.Anchored || !state.ApcPowered || !state.Enabled)
            return "Danger";
        return state.LaserActive ? "Good" : "Caution";
    }

    private static string FormatNumber(double value, int digits = 2)
        => value.ToString($"N{digits}", CultureInfo.CurrentCulture);

    private static string FormatStep(float step)
    {
        if (MathF.Abs(step - MathF.Round(step)) < 0.0005f)
            return MathF.Round(step).ToString(CultureInfo.CurrentCulture);
        return step.ToString("0.###", CultureInfo.CurrentCulture);
    }
}
