- type: entity
  save: false
  id: BaseSpeciesPickupable
  abstract: true
  components:
    - type: Item
      allowDirectHandPickup: false # Disallow directly picking up this entity from the ground
      shape:
        - 0, 0, 6, 4
    - type: RestrictNestingItem
    - type: MultiHandedItem
    - type: CanEscapeInventory
      baseResistTime: 2
